import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Nepo Games",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, user-scalable=no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
